FROM python:3.12-rc-alpine3.16
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN apk update && apk add binutils

ENV FILE_NAME="bssh_musl"

ADD . /app
WORKDIR /app

ENTRYPOINT [ "/app/containers/docker-entrypoint.sh" ]
